weights: yolov5s.pt
cfg: ''
data: surgery.yaml
hyp:
  lr0: 0.01044
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.00052
  warmup_epochs: 2.8344
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.04749
  cls: 0.47871
  cls_pw: 0.98135
  obj: 0.99395
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 3.925
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.74234
  hsv_v: 0.41118
  degrees: 0.0
  translate: 0.09963
  scale: 0.50023
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
  anchors: 3.0
epochs: 40
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp12
